### ISSUE TITLE
Short References don't seem to be working...

### ISSUE THREAD

**Issue by tammersaleh** [miekg/mmark#118]
I don't think short references actually work (or I'm just doing it wrong)...

Input file:

```
# My header {#header}

Lorem ipsum dolor sit amet, at ultricies ...
See Section (#header).
```

Output:

```
<h1 id="header">My header</h1>

<p>Lorem ipsum dolor sit amet, at ultricies ...
See Section <a href="#header"></a>.</p>
```

What I expected to see:

```
<h1 id="header">My header</h1>

<p>Lorem ipsum dolor sit amet, at ultricies ...
See Section <a href="#header">My header</a>.</p>
```
(note the header title in the `<a>` tag)

I'm using mmark version `1.3.6`

**Comment by miekg** [comment]
This was ultimatily done because the XML output for the IETF, re-adds the name, i.e.:
~~~
<section anchor="header" title="My header">
<t>Lorem ipsum dolor sit amet, at ultricies ...
See Section <xref target="header"/>.
</t>
</section>
~~~
When processed by xml2rfc will expand that `xref`. In https://github.com/miekg/learninggo/blob/master/introduction.md I post-process this with javascript to re-add the name.

There is currently no heading-name tracking in mmark, because it is just a one pass parser.
