### ISSUE TITLE
MMark pages don't generate Hugo table of contents

### ISSUE THREAD

**Issue by lucperkins** [miekg/mmark#120]
I wasn't quite sure if I should raise this issue here or in the Hugo repo, but I'd at least like to raise awareness, because I suspect that a large chunk of people using MMark will be doing so via Hugo. Hugo has a [table of contents](https://gohugo.io/content-management/toc/) feature that automatically generates a per-page TOC that can be accessed via the page's `.TableOfContents` attribute. I've attempted to use TOCs for MMark documents in multiple versions of Hugo (I'm currently on `0.25-DEV`) but to no avail.

I'd be happy to try to submit a fix myself. Let me know if you'd prefer that.

**Comment by lucperkins** [comment]
@GregorioMartinez Thanks a lot! I'm going to dig in and see if there's an easy fix for this.

@miekg If you have any pointers on a good place to look first in the codebase, let me know.

**Comment by mikhail73** [comment]
Mmark makes several errors when generating anchors for headers.

— (mdash) generate as `--`

– (ndash) not generate at all

nbsp  not generate at all

**Comment by oblitum** [comment]
As far as I know, @miekg was looking for new maintainers for Mmark due to ENOTIME:

- https://twitter.com/miekg/status/921779231566319617

Maybe it's an opportunity for Hugo to pick it up or fork. I just would find it really sad if it becomes abandoned, my own blog on Hugo is built upon Mmark due to its better support for math.
