### ISSUE TITLE
Offering mmark to Hugo?

### ISSUE THREAD

**Issue by karland** [miekg/mmark#3]
@miekg Hi, I like that you have included quite some useful extensions into `blackfriday`. I also understand, that you offered to backport these extensions into `blackfriday`. Unfortunately the owners of blackfriday did not seem to be interested in order to keep blackfriday simple and pure. I can accept this.

Now I understood from the `hugo` people that they are willing to accept different alternatives to blackfriday and suggest a PR.

[https://github.com/spf13/hugo/issues/836](https://github.com/spf13/hugo/issues/836)

I have no clue how hard it would be to plug mmark into hugo, since I do not code in Go. Would you be interested? Thanks.

**Comment by anthonyfok** [comment]
Hi @karland,

For curiosity sake, I have added a very preliminary/experimental/incomplete support for mmark in Hugo in this experimental branch: https://github.com/anthonyfok/hugo/tree/experimental-mmark-support

Or the patch to Hugo `master` branch here: https://github.com/anthonyfok/hugo/commit/b1094ebdadfeb86d345c1d1c6bdd56e85af5684b

You will either need to name your content files `*.mmark`, or you may continue using the `*.md` extension but add `markup = "mmark"` in each of the `*.md` files you want processed with mmark rather than blackfriday.

Feedback welcome!

**Comment by miekg** [comment]
@anthonyfok that's pretty cool! :) Didn't know people (outside me) were already using it.

**Comment by miekg** [comment]
I still need help with the Html output thought:

* citations
* parts
* abstract
* etc.

still don't have good html output

**Comment by miekg** [comment]
html output is in much better shape ever since I've ported over Learning Go. Closing for now.
